# Generated by Django 4.1.7 on 2023-03-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
